---
name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Firmware
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: mdgreenwald/mozilla-sops-action@d9714e521cbaecdae64a89d2fdd576dd2aa97056 # v1.6.0

      - uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          secrets: |
            github-homelab-esphome-firmware/data/google-cloud region | CLOUDSDK_COMPUTE_REGION ;
            github-homelab-esphome-firmware/data/google-cloud workload_identity_provider | GOOGLE_WORKLOAD_IDENTITY_PROVIDER ;
            github-homelab-esphome-firmware/data/google-cloud ci_service_account | GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT ;
            github-homelab-esphome-firmware/data/google-cloud-storage access_key_id | GCS_ACCESS_KEY_ID ;
            github-homelab-esphome-firmware/data/google-cloud-storage secret_access_key | GCS_SECRET_ACCESS_KEY

      - uses: 'google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6'
        with:
          workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - run: |
          pip install s3cmd --no-cache

      - run: |
          ./scripts/secrets_crypter.sh d

      - uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          tags: builder:latest
          push: false
      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: builder:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            ./scripts/build_firmware.sh

      - run: |
          ./scripts/upload_firmware.sh infrastructure-assets-5274ba70-fde0-47de-8e9a-f1bc64c11157/esphome/firmware
